---
- hosts: 172.31.17.187
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt: 
      name: apache2
      state: present 
    notify: restartedwebserver

  - name: i want to copy the file
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartedwebserver   

  handler: 
    name: i want to restarted webserver 
    servive:
       name: apache2
       state: restarted      