---
- hosts: 172.31.26.59
  become: yes
  vars: 
    myvars01: git
    myvars02: tree
    myvars03: wget

  tasks:
   - name: i want to display git
     debug:
       msg: "{{myvars01}}"

   - name: i want to install tree
     apt:  
       name: "{{myvars02}}"
       state: present

     loop:
      - "{{myvars01}}"   
      - "{{myvars02}}"     
      - "{{myvars03}}"

