---
- hosts: 172.31.17.187
  become: yes
  vars:
    myvars1: git
    myvars2: tree
    myvars3: wget
  tasks:
   - name: i want to display myvars1
     debug:  
        msg: "{{myvars1}}"

   - name: i want to install git
     apt:
       name: "{{git}}"
       state: present