---
- hosts: 172.31.17.187
  become: yes
  vars: 
    myvars01: git
    myvars02: wget
    myvars03: tree
  tasks:
   - name: i want to display 
     debug:
        msg: git  

   - name: i want to install myvars02
     apt: 
       name: "{{myvars02}}"
       state: present

     loop:
       - git
       - wget
       - tree   

