---
- hosts: 172.31.26.59
  become: yes
  vars: 
    myvars01: git
    myvars02: tree
    myvars03: wget

  tasks:
   - name: i want to display git
     debug:
       msg: "{{myvars01}}"
       
         

