---
# tasks file for mywebrole02
- name: install webserver
  apt: 
    name: apache2
    state: present

- name: copy indexfile
  template:
       src: templates/myindex.j2
       dest: /var/www/html/index.html
  notify: restartedwebserver     